name: CI

on:
  push:
  schedule:
  - cron:  '0 1 * * *' # Every day at 1am.

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      ZEPHYR_BASE: /home/runner/work/firefly_zephyr/firefly_zephyr/zephyrproject/zephyr
      ZEPHYR_TOOLCHAIN_VARIANT: gnuarmemb
      GNUARMEMB_TOOLCHAIN_PATH: /home/runner/work/firefly_zephyr/firefly_zephyr/gcc/gcc-arm-none-eabi-10-2020-q4-major
    steps:
      - uses: actions/checkout@v1
      - name: Install Arm GCC
        run: mkdir gcc && cd gcc && wget https://developer.arm.com/-/media/Files/downloads/gnu-rm/10-2020q4/gcc-arm-none-eabi-10-2020-q4-major-x86_64-linux.tar.bz2 && tar xjf gcc-arm-none-eabi-10-2020-q4-major-x86_64-linux.tar.bz2 && cd ..
      - run: sudo apt-get update && sudo apt-get install --no-install-recommends git cmake ninja-build gperf ccache dfu-util device-tree-compiler wget python3-dev python3-pip python3-setuptools python3-tk python3-wheel xz-utils file make gcc gcc-multilib g++-multilib libsdl2-dev
      - run: sudo pip3 install west
      - run: west init zephyrproject --mr v3.1.0 && cd zephyrproject && west update && cd ..
      - run: pip3 install -r ./zephyrproject/zephyr/scripts/requirements.txt
      - run: cd ./zephyrproject/zephyr && source zephyr-env.sh && cd ../..
      - run: west manifest --validate
      - run: west build firefly --pristine && mv ./build/zephyr/zephyr.hex firefly.hex
      - uses: actions/upload-artifact@v1
        with:
          name: firefly.hex
          path: firefly.hex
      - run: west build activator --pristine && mv ./build/zephyr/zephyr.hex activator.hex
      - uses: actions/upload-artifact@v1
        with:
          name: activator.hex
          path: activator.hex
      - run: west build smoke_test --pristine --board firefly_v1 && mv ./build/zephyr/zephyr.hex smoke_test_firefly.hex
      - uses: actions/upload-artifact@v1
        with:
          name: smoke_test_firefly.hex
          path: smoke_test_firefly.hex
      - run: west build smoke_test --pristine --board locket && mv ./build/zephyr/zephyr.hex smoke_test_locket.hex
      - uses: actions/upload-artifact@v1
        with:
          name: smoke_test_locket.hex
          path: smoke_test_locket.hex
      - uses: ncipollo/release-action@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          artifacts: firefly.hex,activator.hex,smoke_test.hex,smoke_test_firefly.hex,smoke_test_locket.hex
          bodyFile: RELEASE.md
          token: ${{ secrets.GITHUB_TOKEN }}
  hardware_test:
    runs-on: self-hosted
    needs: [build]
    if: github.ref == 'never'
    steps:
      - uses: actions/checkout@v1
      - uses: actions/download-artifact@v1
        with:
          name: smoke_test.hex
      - run: stty -F /dev/ttyACM0 115200
      - run: cat /dev/ttyACM0 > log.txt &
      - run: JLinkExe -if SWD -autoconnect 1 -speed 4000 -device nrf52 -CommanderScript smoke_test/flash.jlink
      - run: sleep 10
      - run: cat log.txt
      - run: cat log.txt | grep "PROJECT EXECUTION SUCCESSFUL"
