name: CI

on:
  push:
  schedule:
  - cron:  '0 13 * * *' # Every day at 1pm.

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      ZEPHYR_BASE: /home/runner/work/firefly_zephyr/firefly_zephyr/zephyrproject/zephyr
      ZEPHYR_TOOLCHAIN_VARIANT: gnuarmemb
      GNUARMEMB_TOOLCHAIN_PATH: /home/runner/work/firefly_zephyr/firefly_zephyr/gcc/gcc-arm-none-eabi-10-2020-q4-major
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies via APT
        run: sudo apt-get update && sudo apt-get install --no-install-recommends git cmake ninja-build gperf ccache dfu-util device-tree-compiler wget python3-dev python3-pip python3-setuptools python3-tk python3-wheel xz-utils file make gcc gcc-multilib g++-multilib libsdl2-dev
      - name: Install Arm GCC
        run: mkdir gcc && cd gcc && wget https://developer.arm.com/-/media/Files/downloads/gnu-rm/10-2020q4/gcc-arm-none-eabi-10-2020-q4-major-x86_64-linux.tar.bz2 && tar xjf gcc-arm-none-eabi-10-2020-q4-major-x86_64-linux.tar.bz2 && cd ..
      - name: Download and activate Pigweed
        run: cd .. && git clone https://pigweed.googlesource.com/pigweed/pigweed && source pigweed/bootstrap.sh && cd -
      - name: Install West to Pigweed's virtualenv
        run: pip3 install west
      - name: Download Zephyr RTOS sources
        run: west init zephyrproject --mr v3.2.0 && cd zephyrproject && west update && west zephyr-export && cd -
      - name: Install Zephyr python dependencies to Pigweed's virtualenv
        run: pip3 install -r ./zephyrproject/zephyr/scripts/requirements.txt
      - name: Activate Zephyr environment
        run: cd ./zephyrproject/zephyr && source zephyr-env.sh && cd ../..
      - name: Validate Zephyr environment
        run: west manifest --validate
      - run: source ../pigweed/activate.sh && west build lock_test --pristine --board nrf52840dk_nrf52840 && mv ./build/zephyr/zephyr.hex lock_test.hex
      - uses: actions/upload-artifact@v1
        with:
          name: lock_test.hex
          path: lock_test.hex
      - run: west build firefly --pristine && mv ./build/zephyr/zephyr.hex firefly.hex
      - uses: actions/upload-artifact@v1
        with:
          name: firefly.hex
          path: firefly.hex
      - run: west build activator --pristine && mv ./build/zephyr/zephyr.hex activator.hex
      - uses: actions/upload-artifact@v1
        with:
          name: activator.hex
          path: activator.hex
      - run: west build smoke_test --pristine --board firefly_v1 && mv ./build/zephyr/zephyr.hex smoke_test_firefly.hex && mv ./build/zephyr/zephyr.elf smoke_test_firefly.elf
      - uses: actions/upload-artifact@v1
        with:
          name: smoke_test_firefly.hex
          path: smoke_test_firefly.hex
      - uses: actions/upload-artifact@v1
        with:
          name: smoke_test_firefly.elf
          path: smoke_test_firefly.elf
      - run: west build smoke_test --pristine --board locket && mv ./build/zephyr/zephyr.hex smoke_test_locket.hex
      - uses: actions/upload-artifact@v1
        with:
          name: smoke_test_locket.hex
          path: smoke_test_locket.hex
      - uses: ncipollo/release-action@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          artifacts: firefly.hex,activator.hex,smoke_test.hex,smoke_test_firefly.hex,smoke_test_locket.hex
          bodyFile: RELEASE.md
          token: ${{ secrets.GITHUB_TOKEN }}
  hardware_test:
    runs-on: self-hosted
    needs: [build]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/download-artifact@v1
        with:
          name: smoke_test_firefly.elf
      - run: stty -F /dev/ttyACM1 115200
      - run: cat /dev/ttyACM1 > log.txt &
      - run: gdb-multiarch -nx --batch -ex 'target extended-remote /dev/ttyACM0' -ex 'monitor swdp_scan' -ex 'attach 1' -ex 'load' -ex 'compare-sections' -ex 'kill' smoke_test_firefly.elf/smoke_test_firefly.elf
      - run: sleep 10
      - run: cat log.txt
      - run: cat log.txt | grep "All tests passed!"
