name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ZEPHYR_BASE: /home/runner/work/firefly_zephyr/firefly_zephyr/zephyrproject/zephyr
      ZEPHYR_TOOLCHAIN_VARIANT: zephyr
      ZEPHYR_SDK_INSTALL_DIR: /home/runner/work/firefly_zephyr/firefly_zephyr/zephyr-sdk-0.11.1
    steps:
      - uses: actions/checkout@v1
      - run: sudo apt-get install --no-install-recommends gcc-arm-none-eabi git cmake ninja-build gperf ccache dfu-util device-tree-compiler wget python3-pip python3-setuptools python3-tk python3-wheel xz-utils file make gcc gcc-multilib g++-multilib libsdl2-dev
      - run: sudo pip3 install west
      - run: west init zephyrproject && cd zephyrproject && west update && cd ..
      - run: pip3 install -r ./zephyrproject/zephyr/scripts/requirements.txt
      - run: wget https://github.com/zephyrproject-rtos/sdk-ng/releases/download/v0.11.1/zephyr-sdk-0.11.1-setup.run && chmod +x zephyr-sdk-0.11.1-setup.run && ./zephyr-sdk-0.11.1-setup.run -- -d /home/runner/work/firefly_zephyr/firefly_zephyr/zephyr-sdk-0.11.1
      - run: cd ./zephyrproject/zephyr && source zephyr-env.sh && cd ../..
      - run: west manifest --validate
      - run: west --help
      - run: west build firefly --pristine
      - uses: actions/upload-artifact@v1
        with:
          name: firefly.hex
          path: ./build/zephyr/zephyr.hex
      - run: west build activator --pristine
      - uses: actions/upload-artifact@v1
        with:
          name: activator.hex
          path: ./build/zephyr/zephyr.hex
      - run: west build smoke_test --pristine
      - uses: actions/upload-artifact@v1
        with:
          name: smoke_test.hex
          path: ./build/zephyr/zephyr.hex