name: CI

on:
  push:
  schedule:
  - cron:  '0 13 * * *' # Every day at 1pm.

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      ZEPHYR_BASE: /home/runner/work/firefly_zephyr/firefly_zephyr/third_party/zephyr
      ZEPHYR_TOOLCHAIN_VARIANT: gnuarmemb
      GNUARMEMB_TOOLCHAIN_PATH: /home/runner/work/firefly_zephyr/firefly_zephyr/third_party/pigweed/environment/cipd/packages/arm
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies via APT
        run: sudo apt-get update && sudo apt-get install --no-install-recommends gperf dfu-util device-tree-compiler wget xz-utils file libsdl2-dev
      - name: Install West globally
        run: pip3 install west
      - name: Download dependencies (including Zephyr RTOS, Pigweed and nRF Connect SDK)
        run: west init -l manifest && west update && west zephyr-export
      - name: Bootstrap and activate Pigweed
        run: source third_party/pigweed/bootstrap.sh
      - name: Install Zephyr python dependencies to Pigweed's virtualenv
        run: pip3 install -r ./third_party/zephyr/scripts/requirements.txt
      - name: Install NRF python dependencies to Pigweed's virtualenv
        run: pip3 install -r ./third_party/nrf/scripts/requirements.txt
      - name: Install McuBoot python dependencies to Pigweed's virtualenv
        run: pip3 install -r ./third_party/bootloader/mcuboot/scripts/requirements.txt
      - name: Activate Zephyr environment
        run: source third_party/zephyr/zephyr-env.sh
      - name: Validate Zephyr environment
        run: west manifest --validate
      - run: source ./third_party/pigweed/activate.sh && west build firmware/lock_test --pristine --board lock_v01 && mv ./build/zephyr/zephyr.elf lock_test.elf
      - uses: actions/upload-artifact@v1
        with:
          name: lock_test.elf
          path: lock_test.elf
      - run: source ./third_party/pigweed/activate.sh && west build firmware/lock --pristine --board lock_v01 && mv ./build/zephyr/zephyr.hex lock.hex
      - uses: actions/upload-artifact@v1
        with:
          name: lock.hex
          path: lock.hex
      - run: source ./third_party/pigweed/activate.sh && west build firmware/firefly --pristine && mv ./build/zephyr/zephyr.elf firefly.elf
      - uses: actions/upload-artifact@v1
        with:
          name: firefly.elf
          path: firefly.elf
      - run: source ./third_party/pigweed/activate.sh && west build firmware/activator --pristine && mv ./build/zephyr/zephyr.elf activator.elf
      - uses: actions/upload-artifact@v1
        with:
          name: activator.elf
          path: activator.elf
      - run: source ./third_party/pigweed/activate.sh && west build firmware/smoke_test --pristine --board firefly_v1 && mv ./build/zephyr/zephyr.elf smoke_test_firefly.elf
      - uses: actions/upload-artifact@v1
        with:
          name: smoke_test_firefly.elf
          path: smoke_test_firefly.elf
      - uses: ncipollo/release-action@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          artifacts: firefly.hex,activator.hex,smoke_test.hex,smoke_test_firefly.hex
          bodyFile: RELEASE.md
          token: ${{ secrets.GITHUB_TOKEN }}
  hardware_test:
    runs-on: self-hosted
    needs: [build]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/download-artifact@v1
        with:
          name: smoke_test_firefly.elf
      - run: stty -F /dev/ttyACM3 115200
      - run: cat /dev/ttyACM3 > log.txt &
      - run: gdb-multiarch -nx --batch -ex 'target extended-remote /dev/ttyACM2' -ex 'monitor swdp_scan' -ex 'attach 1' -ex 'load' -ex 'compare-sections' -ex 'kill' smoke_test_firefly.elf/smoke_test_firefly.elf
      - run: sleep 10
      - run: cat log.txt
      - run: cat log.txt | grep "All tests passed!"
      - uses: actions/download-artifact@v1
        with:
          name: lock_test.elf
      - run: stty -F /dev/ttyACM1 115200
      - run: cat /dev/ttyACM1 > log.txt &
      - run: gdb-multiarch -nx --batch -ex 'target extended-remote /dev/ttyACM0' -ex 'monitor swdp_scan' -ex 'attach 1' -ex 'load' -ex 'compare-sections' -ex 'kill' lock_test.elf/lock_test.elf
      - run: sleep 10
      - run: cat log.txt
      - run: cat log.txt | grep "All tests passed!"
